stages:
  - publish
  - release
  - cleanup
  - notify
  - test

mirror:
  stage: publish
  script:
    - setsid ./ci/mirror.sh
  only:
    - /^(main.*)$/
  tags:
    - mirror

release:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_REGISTRY: $CI_REGISTRY
    DOCKER_USERNAME: $CI_REGISTRY_USER
    DOCKER_PASSWORD: $CI_REGISTRY_PASSWORD
    GITLAB_TOKEN: $GITLAB_TOKEN
    GIT_DEPTH: 0
  only:
    refs:
      - tags
  script:
    - chmod +x ./ci/release.sh
    - ./ci/release.sh
  tags:
    - imagesbuilder

cleanup:
  stage: cleanup
  only:
    refs:
      - tags
  script:
    - chmod +x ./ci/cleanup.sh
    - ./ci/cleanup.sh
  tags:
    - imagesbuilder

notify:
  stage: notify
  only:
    refs:
      - tags
  script:
    - chmod +x ./ci/notify.sh
    - ./ci/notify.sh
  tags:
    - imagesbuilder

test:
  stage: test
  only:
    refs:
      - /^(main.*|develop.*)$/
      - merge_requests
  script:
    - chmod +x ./ci/test.sh
    - ./ci/test.sh
  tags:
    - imagesbuilder
