builds:
  - binary: cwc
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.Version={{.Version}}

archives:
  -
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - install.sh
      - README.md
release:
  prerelease: auto

gitlab_urls:
  api: https://gitlab.comwork.io/api/v4
  download: https://gitlab.comwork.io
  # set to true if you use a self-signed certificate
  skip_tls_verify: true
  # set to true if you want to upload to the Package Registry rather than attachments
  # Only works with GitLab 13.5+
  use_package_registry: false

universal_binaries:
  - replace: true

dockers:
- image_templates: ["rg.fr-par.scw.cloud/comworkio/cwc:{{ .Version }}"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://gitlab.comwork.io/oss/cwcloud/cwc
  - --label=org.opencontainers.image.source=https://gitlab.comwork.io/oss/cwcloud/cwc
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{.Date}}"
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT

brews:
  -
    name: cwc
    homepage: https://gitlab.comwork.io/oss/cwcloud/cwc
    tap:
      owner: oss
      name: cwcloud/homebrew-cwc
    commit_author:
      name: comwork
      email: contact@comwork.io
  - 
    url_template: "https://gitlab.comwork.io/oss/cwcloud/cwc/-/releases/{{ .Tag }}/{{ .ArtifactName }}"

checksum:
  name_template: 'checksums.txt'
