version: 2

builds:
  - binary: cwc
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.Version={{.Version}}

universal_binaries:
  - replace: true

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - install.sh
      - README.md

release:
  prerelease: auto
  #? Added mode for GitLab compatibility
  mode: replace

checksum:
  name_template: 'checksums.txt'

dockers:
  - image_templates: 
      - "rg.fr-par.scw.cloud/comworkio/cwc:{{ .Version }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://gitlab.comwork.io/oss/cwcloud/cwc
      - --label=org.opencontainers.image.source=https://gitlab.comwork.io/oss/cwcloud/cwc
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

gitlab_urls:
  api: https://gitlab.comwork.io/api/v4
  download: https://gitlab.comwork.io
  skip_tls_verify: true
  use_package_registry: false

brews:
  - name: cwc
    homepage: https://gitlab.comwork.io/oss/cwcloud/cwc
    repository:
      owner: cwc
      name: cwcloud/homebrew-cwc
    commit_author:
      name: comwork
      email: contact@comwork.io
    url_template: "https://gitlab.comwork.io/oss/cwcloud/cwc/-/releases/{{ .Tag }}/{{ .ArtifactName }}"

#? Added changelog configuration for better release notes
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge branch
      - Merge pull request
