builds:
  - binary: cwc
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

gitlab_urls:
  api: https://gitlab.comwork.io/api/v4
  download: https://gitlab.comwork.io
  # set to true if you use a self-signed certificate
  skip_tls_verify: true
  # set to true if you want to upload to the Package Registry rather than attachments
  # Only works with GitLab 13.5+
  use_package_registry: false


universal_binaries:
  - replace: true

brews:
  -
    name: cwc
    homepage: https://gitlab.comwork.io/oss/cwc/cwc
    tap:
      owner: oss/cwc
      name: homebrew-cwc
    commit_author:
      name: amirghedira
      email: amirghedira06@gmail.com
  - 
    url_template: "http://gitlab.comwork.io/oss/cwc/cwc/-/releases/{{ .Tag }}/{{ .ArtifactName }}"
checksum:
  name_template: 'checksums.txt'
